class StudySession {
  final int? sessionId;
  final String title;
  final String moduleCode;
  final String moduleName;
  final String dayOfWeek;
  final String startTime;
  final String endTime;
  final String? venue;
  final String sessionType; // 'study', 'revision', 'assignment', 'exam_prep'
  final String? notes;
  final int? duration; // Duration in minutes
  final DateTime createdAt;
  final bool isAutoGenerated;

  StudySession({
    this.sessionId,
    required this.title,
    required this.moduleCode,
    required this.moduleName,
    required this.dayOfWeek,
    required this.startTime,
    required this.endTime,
    this.venue,
    required this.sessionType,
    this.notes,
    this.duration,
    DateTime? createdAt,
    this.isAutoGenerated = false,
  }) : createdAt = createdAt ?? DateTime.now();

  factory StudySession.fromJson(Map<String, dynamic> json) {
    return StudySession(
      sessionId: json['session_id'],
      title: json['title'] ?? '',
      moduleCode: json['module_code'] ?? '',
      moduleName: json['module_name'] ?? '',
      dayOfWeek: json['day_of_week'] ?? '',
      startTime: json['start_time'] ?? '',
      endTime: json['end_time'] ?? '',
      venue: json['venue'],
      sessionType: json['session_type'] ?? 'study',
      notes: json['notes'],
      duration: json['duration'],
      createdAt: json['created_at'] != null 
          ? DateTime.parse(json['created_at']) 
          : DateTime.now(),
      isAutoGenerated: json['is_auto_generated'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'session_id': sessionId,
      'title': title,
      'module_code': moduleCode,
      'module_name': moduleName,
      'day_of_week': dayOfWeek,
      'start_time': startTime,
      'end_time': endTime,
      'venue': venue,
      'session_type': sessionType,
      'notes': notes,
      'duration': duration,
      'created_at': createdAt.toIso8601String(),
      'is_auto_generated': isAutoGenerated,
    };
  }

  StudySession copyWith({
    int? sessionId,
    String? title,
    String? moduleCode,
    String? moduleName,
    String? dayOfWeek,
    String? startTime,
    String? endTime,
    String? venue,
    String? sessionType,
    String? notes,
    int? duration,
    DateTime? createdAt,
    bool? isAutoGenerated,
  }) {
    return StudySession(
      sessionId: sessionId ?? this.sessionId,
      title: title ?? this.title,
      moduleCode: moduleCode ?? this.moduleCode,
      moduleName: moduleName ?? this.moduleName,
      dayOfWeek: dayOfWeek ?? this.dayOfWeek,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      venue: venue ?? this.venue,
      sessionType: sessionType ?? this.sessionType,
      notes: notes ?? this.notes,
      duration: duration ?? this.duration,
      createdAt: createdAt ?? this.createdAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }
}







